[package]
name = "cjd"
description = "Convert between various JSON-like data formats"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "^0.3.20"
structopt-utilities = "^0.0.8"
pipe-trait = "^0.2.1"
serde = "^1.0.117"
serde_json = "^1.0.59"
serde_yaml = "^0.8.14"
toml = "^0.5.7"
json5 = "^0.3.0"
