[package]
name = "cjd"
description = "Convert between various JSON-like data formats"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "^0.3.25"
structopt-utilities = "^0.1.0"
pipe-trait = "^0.3.2"
serde = "^1.0.131"
serde_json = "^1.0.72"
serde_yaml = "^0.8.21"
toml = "^0.5.8"
json5 = "^0.4.1"
