[package]
name = "is-port-free"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "^3.2.18", features = ["derive"] }
portpicker = "^0.1.1"
pipe-trait = "^0.4.0"
