[package]
name = "break-line"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "^4.1.2", features = ["derive"] }
pipe-trait = "^0.4.0"

[dev-dependencies]
command-extra = "^1.0.0"
