[package]
name = "break-line"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "^0.3.22"
structopt-utilities = "^0.0.8"
pipe-trait = "^0.3.2"

[dev-dependencies]
command-extra = "^1.0.0"
