[package]
name = "find-virtual-display"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "^3.2.16", features = ["derive"] }
pipe-trait = "^0.4.0"
