[package]
name = "find-virtual-display"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "^0.3.21"
structopt-utilities = "^0.0.8"
pipe-trait = "^0.2.1"
