[package]
name = "script"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "^4.1.7", features = ["derive"] }
cargo_toml = "^0.14.1"
pipe-trait = "^0.4.0"
