[package]
name = "find-executable"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
serde_json = "1.0.87"
which = "4.3.0"
os_display = "0.1.3"
libc = "0.2.139"
